### PR TITLE
Fixed strange wording

### PR DESCRIPTION
**Pull request by miestrode**
Whilst reading this part, I found the wording here to be both incorrect and cumbersome, unless I somehow misunderstood it. This PR changes it to fix that issue.

### CODE REVIEW

**Comment by MatthijsBlom** [comment]
This looks good to me. Thanks!

It looks like this chapter needs updating: these days `catch :: Exception e => IO a -> (e -> IO a) -> IO a` instead of `catch :: IO a -> (IOError -> IO a) -> IO a`.

**Comment by miestrode** [comment]
I honestly agree. As another example, the chapter is also outdated in the functions it uses for RNG. From what I know, one should use `uniform`, not `random` these days.

I might make a PR fixing this issue alongside others.

**Comment by smith558** [comment]
> I honestly agree. As another example, the chapter is also outdated in the functions it uses for RNG. From what I know, one should use `uniform`, not `random` these days.
> 
> I might make a PR fixing this issue alongside others.

That'd be awesome if you do find time to open that PR!

**Comment by MatthijsBlom** [comment]
By all means feel free to open issues for any problems you encounter, even if only to point them out to others.

**Comment by smith558** [comment]
@miestrode Thank you for your contribution! 🙂

**Pull request merged**
