### PR TITLE
"guys" -> "people"

### PR DESCRIPTION
**Pull request by samtygier**
Current text has "Haskell was made by some really smart guys". The Haskell committees and developers are not all men. Even if they were, ungendered language is better.

(PS it would be nice for the repo to only have a single copy of eveything)

### CODE REVIEW

**Comment by MatthijsBlom** [comment]
"guy"/"guys" also appears in the chapters _Making Our Own Types and Typeclasses_ and _Modules_. In most cases "folks" seems like a fine substitute.

**Comment by ulysses4ever** [comment]
+1 for _folks_

**Comment by samtygier** [comment]
Yes, "folks" is good for those greetings. Are you happy with "smart people" for the first one?

There is also the "And like, sometimes me and the boys say that `Maybe` is a type ...". Maybe "me and my buddies" fits with the style? But also "my buddies and I" would be more correct. Maybe the whole sentence should be replaced with something clearer, though is feels a shame to loose the fun style of the original text.

**Comment by MatthijsBlom** [comment]
"smark folks" seems fun-y-er to me.

I fail to come up with alternatives to "me and the boys" / "me and the gals" that sound as good.

**Comment by samtygier** [comment]
I've gone with buddies.

I've also change the phonebook example. (With a subtle reference to maps).

Happy to make any further tweaks.

**Review by smith558 — APPROVED** [review]

**Review by learnyouahaskell — APPROVED** [review]

**Review by konsumlamm — APPROVED** [review]

**Comment by smith558** [comment]
@samtygier Thank you for your contribution 🙂

**Pull request merged**
