### PR TITLE
Repair lines

### PR DESCRIPTION
**Pull request by memowe**
*Some* HTML files had *some* DOS line endings (CRLF instead of LF). I used
- `dos2unix docs/*.html` to convert line endings
- `sed -i 's/[ \t]*$//' docs/*.html` to remove trailing white spaces

Unfortunately the resulting diffs are unreadable. I suggest trying the same steps and comparing with my results before merging to make sure these commits don't break anything.

### CODE REVIEW

**Comment by smith558** [comment]
@memowe would you mind looking at some of the merge conflicts with main which appeared on your branch? so we can merge this smoothly 🙂

**Comment by memowe** [comment]
> @memowe would you mind looking at some of the merge conflicts

Of course. Instead of trying to merge I will pull the external changes and run my commands again as my diffs look horrible. ;)

**Comment by memowe** [comment]
@smith558 Done. :) But please have a good look whether these commits break anything. I used exactly the commands documented here and in the commits.

**Comment by smith558** [comment]
@memowe Thank you for your contribution! 🙂

**Pull request merged**
