### PR TITLE
Grammar typos spelling flow

### PR DESCRIPTION
**Pull request by chrisdenman**
Lots of minor improvements: grammar, spelling, typos, standard English stuff...

I've tried to honour the style of the original author whilst applying these corrections. I like the original playful style.

### CODE REVIEW

**Review by memowe — APPROVED** [review]
First of all I'm very sorry for the late reply. I was on vacation for several weeks and just got back to the office.

I am not a native speaker so I invite everyone to have a look at these changes, but most of it seems very sensible to me. It's a lot of work and this project needs volunteers like you willing to invest time. Thank you very much!

**Comment by chrisdenman** [comment]
Hi @memowe!

Thank you for your approval and I appreciate your kind words. There's no need to apologise and I'm glad you had a good long holiday :).

I shall start a discussion before long about how we can progress the work on the Semigroup/Monoid changes needed.

Thanks again.

**Review by smith558 — APPROVED** [review]

**Comment by smith558** [comment]
Thank you for your contribution! 🙂 @chrisdenman

**Comment by chrisdenman** [comment]
Thank you so much! I'm really happy this was accepted and merged.

**Pull request merged**
