### PR TITLE
fix a couple of typos

### PR DESCRIPTION
**Pull request by chad3814**
* on the homepage it says `be` instead of `by`
* on the 'Higher Order Functions' page it says
  > Let's answer us this question: How many elements does it take for the sum of the roots of all natural numbers to exceed 1000? To get the squares of all natural numbers, we just do map sqrt [1..]. 
  * That should be `To get the square roots of all natural numbers`

### CODE REVIEW

**Review by memowe — APPROVED** [review]
Thank you very much for your contribution! ❤️

PS: sorry for the delayed reply, I just got back from vacation.

**Review by smith558 — APPROVED** [review]

**Comment by smith558** [comment]
Thank you for your contribution! 🙂 @chad3814

**Comment by smith558** [comment]
Thanks for the review!! @memowe

**Comment by chad3814** [comment]
thanks everyone, I'm just learning me a haskell…

**Pull request merged**
